### PR TITLE
Fixed display error in table builder

### PR DESCRIPTION
**Pull request by samin-batra**
This fixes the display error while showing tables using table_builder.

### CODE REVIEW

**Comment by samin-batra** [comment]
Fixes issue #84

**Comment by skekre98** [comment]
Hi @samin-batra, I appreciate you taking up this issue. Can you post a screenshot of what this returns with the following:
```python
from lab.table_builder import TableBuilder

col_labels = ["Name", "Points", "Rebounds"]
tb = TableBuilder(col_labels)
rows = [
    ["Lebron James", 22.0, 6.0],
    ["Kevin Durant", 21.0, 7.0],
    ["Jimmy Butler", 20.0, 8.0]
]

for row in rows:
    tb.add_row(row)
tb.build_table()
tb.display()
```

**Comment by samin-batra** [comment]
image
@skekre98 here you go

**Review by skekre98 — APPROVED** [review]
LGTM!

**Pull request merged**
