### PR TITLE
Added function definitions for table_builder and add_row to fix #68

### LINKED ISSUE #68: Implement build_table in TableBuilder
**Description of feature/enhancement**
Implement a general purpose function to build a table from the data being passed into the object such as _rows_ and _column_labels_.

**Description of implementation**
https://github.com/skekre98/NBA-Search/blob/b036b35aec8b4703ed899d6dd7fb0cbcb8c46d6f/lab/table_builder.py#L12-L14
This function should add the column labels and rows to the table. This data should then be loaded into the _plot_(see Visualizer) variable. Functions such as display and clear have already been implemented in the parent class. This function should be implemented with the `matplotlib` library.

**Why this is a good feature/enhancement**
Will help in running data oriented experiments.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by samin-batra**
This PR includes a feature to display data in a table for better data analysis. This is to fix issue #68 
This feature has a function called build_table. The function takes a 2D list as data and plots it in the form of a table using Matplotlib. In addition, a function has also been included to add rows individually.
This feature may help in the future to better understand the data and analyze it.

### CODE REVIEW

**Review by skekre98 — CHANGES_REQUESTED** [review]
Looks close, just a few pointers:

TableBuilder is a subclass of Visualizer so you don't need to create a new one. TableBuilder has access to all the class variables of Visualizer from `super().__init__()`, so instead of `visualize.plt.table` you can say `self.plt.table`

I'm not too familiar with matplotlib tables, but if this formatting is necessary, `cell_txt.append([f'{cell}' for cell in row])`, lets just move this functionality to `add_row`

You can also remove the ` visualize.display()`, the user may want to call this away from building the table.

Besides that everything looks really good!

**Comment by samin-batra** [comment]
@skekre98 I have made the suggested changes. One request. When you add "hacktoberfest-accepted" label to the PR? It'd count towards my contributions.

**Comment by skekre98** [comment]
Sure, this looks great. I'll go ahead and approve. Feel free to merge whenever it looks ready.

**Review by skekre98 — APPROVED** [review]

**Comment by samin-batra** [comment]
@skekre98 Thanks a lot! I enjoyed working on this and look forward to working more whenever time permits. :)

**Pull request merged**
