### PR TITLE
Removed usage of os.system() and used modules instead

### PR DESCRIPTION
**Pull request by abhijeetsharma200**
Fix issue #132 by removing the usage of `os.system()` and refactored the code to use Modules.

### CODE REVIEW

**Review by skekre98 — COMMENTED** [review]
Hi @abhijeetsharma200, this looks very close, but there seems to be a small bug when loading the `spacy` model. I think it will require some configuration with the path variable. Please see these logs:

```bash
NBA-Search) sharvilkekre$ git branch
  master
* test-pr-144
NBA-Search) sharvilkekre$ python main.py test
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import tests.flask_tests as flask_tests
  File "$HOME/projects/NBA-Search/tests/flask_tests.py", line 3, in <module>
    from app import app
  File "$HOME/projects/NBA-Search/app.py", line 1, in <module>
    from modules.analysis import isNBA
  File "$HOME/projects/NBA-Search/modules/analysis.py", line 9, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
NBA-Search) sharvilkekre$ python main.py run
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import tests.flask_tests as flask_tests
  File "$HOME/projects/NBA-Search/tests/flask_tests.py", line 3, in <module>
    from app import app
  File "$HOME/projects/NBA-Search/app.py", line 1, in <module>
    from modules.analysis import isNBA
  File "$HOME/projects/NBA-Search/modules/analysis.py", line 9, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
NBA-Search) sharvilkekre$ python main.py data
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import tests.flask_tests as flask_tests
  File "$HOME/projects/NBA-Search/tests/flask_tests.py", line 3, in <module>
    from app import app
  File "$HOME/projects/NBA-Search/app.py", line 1, in <module>
    from modules.analysis import isNBA
  File "$HOME/projects/NBA-Search/modules/analysis.py", line 9, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
NBA-Search) sharvilkekre$ git checkout master
M	inference/models/classifiers/query_classifier.pkl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
NBA-Search) sharvilkekre$ python main.py run
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 ```

**Comment by abhijeetsharma200** [comment]
I have been using venv instead of anaconda for testing as seen here.
As such I am confused how changing that `$PATH` in my device will fix this problem as the system $PATH is in `/usr/local/bin` which is not connected to git.

`(.nba) abhi@abhi-VirtualBox:~/NBA-Search$ git branch 
* Fix-Issue-132
  master
(.nba) abhi@abhi-VirtualBox:~/NBA-Search$ python main.py test
Flask Tests
----------------------------------------------------------------------
Ran 14 tests in 3.316s

OK
Module Tests
----------------------------------------------------------------------
Ran 11 tests in 25.802s

OK
Inference Tests
----------------------------------------------------------------------
Ran 15 tests in 53.414s

OK
(.nba) abhi@abhi-VirtualBox:~/NBA-Search$ whereis spacy
spacy: /home/abhi/.nba/bin/spacy
(.nba) abhi@abhi-VirtualBox:~/NBA-Search$ echo $PATH
/home/abhi/.nba/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`

**Comment by skekre98** [comment]
> I have been using venv instead of anaconda for testing as seen here.
I think you are right, this may indeed be an issue with my anaconda setup. It would explain why the CI tests are succeeding.

**Review by skekre98 — APPROVED** [review]
@abhijeetsharma200 Great work! I'll go ahead and merge the PR.

**Pull request merged**
