### PR TITLE
Update preprocess.py

### PR DESCRIPTION
**Pull request by rupeshpalwadi**
modified "query2 = "what is {} {}s {}, stat\n".format(name, action, "%")"

### CODE REVIEW

**Comment by skekre98** [comment]
Can remove the current training data in `../data/query.csv` and run `preprocess.py`. I'd like to see what kind of queries this produces end to end.

**Comment by rupeshpalwadi** [comment]
`what is Kyle O'Quinn rebounds %, stat`

`what is Trey steals %, stat`

**Comment by skekre98** [comment]
Cool, will update `query.csv` merge

**Review by skekre98 — DISMISSED** [review]

**Comment by skekre98** [comment]
@rupeshpalwadi your fork is outdated so tests are failing. See **Update Fork** in [Contribution** Guide](https://github.com/skekre98/NBA-Search/blob/master/CONTRIBUTING.md) and remerge with upstream master. Sorry for the inconvenience.

**Comment by skekre98** [comment]
@rupeshpalwadi your fork is still out of date.
Screen Shot 2020-10-01 at 7 52 57 PM

Run the following commands to set upstream remote and rebase with you master branch:

- `git remote add upstream https://github.com/skekre98/NBA-Search.git `
- `git fetch upstream`
- `git rebase upstream/master`

**Comment by skekre98** [comment]
Awesome thanks for fixing this 😄.

**Review by skekre98 — APPROVED** [review]

**Pull request merged**
