### PR TITLE
renovated chatbox with autoscroll and update

### PR DESCRIPTION
**Pull request by kelaaron**
Created new chatbox with features such as autoscroll and message saving.

### CODE REVIEW

**Comment by skekre98** [comment]
Hi @kelaaron, could you post a screenshot of what the new chatbox looks like?

**Comment by kelaaron** [comment]
Sure, attached is a screenshot. I also just pushed a commit which clears input before waiting for chatbot's response. Let me know if you see anything I should update :)
Screen Shot 2020-11-12 at 4 02 32 PM

**Comment by skekre98** [comment]
@kelaaron Awesome, looks really great! Is there a way to make the send button orange and completely fill the bottom right corner? 

Also not an issue with your PR, but it seems there is a bug in StatNode. The responses seem to be created incorrectly, so I'll open some issues for that on mind end. Thanks for making them apparent 😄

**Comment by kelaaron** [comment]
@skekre98 sounds good, just made requested changes to the send button! 😄

**Review by skekre98 — APPROVED** [review]
Awesome, LGTM!

**Pull request merged**
